# This file contains all parameters related to the manipulator controller

# Provides the name of the group MoveIt is going to run
# If you are not using the provided MoveIt! based grasp controller embedded in this framework, you can ignore this field
manipulator_group_name: "ezgripper"
# The name of the action_server the client should reach. If you are using your own controller make sure to chage this field
action_server_name: "moveit_action_grasp"
# Name of the package contaning the action server to run (if you are using yours please change this field)
# If you are using a plugin please set this field to ""
package_action_server: "smart_manipulation_framework_core"
# Name of the node in which the action server is launched (if you are using yours please change this field)
# You can ignore this field if you are using a plugin
node_action_server_name: "run_moveit_grasp_action_server"
# Type of the node in which the action server is launched (can be a .py file if written in python)
# You can ignore this field if you are using a plugin
action_server_type: "run_moveit_grasp_action_server"
# Specifies the maximum torque to apply when manipulating objects
max_torque: 400
