# Declare the properties of the vision sensor
fixed_kinect:
  frame_id: "simulated_kinect2"
  origin_frame_id: "world"
  # Depth camera's pose
  frame_x: -0.1645
  frame_y: 0.375
  frame_z: 2.72
  # Depth camera's orientation (RPY system, in radians)
  frame_roll: 3.14159265359
  frame_pitch: 0
  frame_yaw: -1.57079632679

# Define the name of the topics on which the input data will be published
pointcloud_topic_name: "simulated_kinect2/pointcloud"
depth_image_topic_name: "simulated_kinect2/depth_image"
rgb_image_topic_name: "simulated_kinect2/rgb_image"
