sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /simulated_kinect2/pointcloud
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: moveit_plugin_filtered

octomap_frame: "simulated_kinect2"
octomap_resolution: 0.05
max_range: 5.0
